### ISSUE TITLE
CI/CD integration

### ISSUE THREAD

**Issue by omoskovko** [fedorchukdmytro/test_global#1]
Is it possible to create workflow using GitHub Action for this project?
Can you solve it?

**Comment by fedorchukdmytro** [comment]
Please take a look on latest workflow.

**Comment by omoskovko** [comment]
Good job

**Comment by omoskovko** [comment]
Link which can help you to prepare for today interview https://www.linkedin.com/posts/oleksandr-moskovko_python-interview-questions-activity-6876966118825705472-0aHQ
